# Generated by Django 6.0.5 on 2026-05-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student/Elev'), ('tutor', 'Tutor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
