# Generated by Django 6.0.5 on 2026-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_academicprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='day_of_week',
            field=models.CharField(default='Luni', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
    ]
