# Generated by Django 6.0.5 on 2026-05-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill_day_of_week_skill_end_time_skill_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
