# Generated by Django 6.0.5 on 2026-05-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='start_time',
        ),
        migrations.CreateModel(
            name='SkillAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.skill')),
            ],
        ),
    ]
