# Generated by Django 6.0.5 on 2026-05-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_skill_day_of_week_remove_skill_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillavailability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='skillavailability',
            name='available_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
