# Generated by Django 6.0.5 on 2026-05-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_alter_tutoringrequest_status_tutoringsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringrequest',
            name='requested_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringrequest',
            name='requested_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
